apiVersion: v1
kind: Service
metadata:
  name: contactcache
spec:
  ports:
    - port: 443
      name: https
  selector:
    run: contactcache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactcache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactcache
  template:
    metadata:
      labels:
        version: v1
        run: contactcache
        app: contactcache
        service: contactcache
        tier: middlewear
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9102"
    spec:
      containers:
        - name: contactcache
          image: tcfw/contactcache:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: "/config/"
          ports:
            - containerPort: 443
            - containerPort: 9102
      volumes:
        - name: config
          secret:
            secretName: contactcache
---
apiVersion: v1
kind: secret
metadata:
  name: contactcache
type: Opaque
data:
  config.yaml: Q0hBTkdFIE1F
